# reports.py
import datetime
import os
from config import OUTPUT_FILENAME

def print_summary(summary: dict, filepath: str):
    """
    Prints a formatted summary to the terminal.
    """
    print("\n" + "="*40)
    print(f" LOG ANALYSIS SUMMARY: {os.path.basename(filepath)}")
    print("="*40)
    
    print(f"Total Lines Analyzed: {summary['total_lines']}")
    print("\n--- Event Counts ---")
    for k, v in summary['counts'].items():
        print(f"  {k}: {v}")
        
    print("\n--- Top Active IPs ---")
    if not summary['top_ips']:
        print("  None detected.")
    for ip, count in summary['top_ips']:
        print(f"  {ip} ({count} events)")
        
    print("\n--- Suspicious Activity ---")
    if not summary['suspicious_activity']:
        print("  ✅ No highly suspicious activity detected based on thresholds.")
    else:
        for alert in summary['suspicious_activity']:
            print(f"  {alert}")
            
    print("="*40 + "\n")

def export_markdown_report(summary: dict, filepath: str) -> str:
    """
    Exports the analysis results to a Markdown file.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"# Log Analysis Security Report\n\n"
    content += f"**Source File:** `{os.path.basename(filepath)}`\n"
    content += f"**Generated On:** {timestamp}\n\n"
    content += "---\n\n"
    
    content += f"## 📊 Summary Statistics\n"
    content += f"- **Total Events Analyzed:** {summary['total_lines']}\n"
    for k, v in summary['counts'].items():
        content += f"- **{k.capitalize()}s:** {v}\n"
        
    content += f"\n## 🌐 Top Active IPs\n"
    if summary['top_ips']:
        content += "| IP Address | Event Count |\n"
        content += "|---|---|\n"
        for ip, count in summary['top_ips']:
            content += f"| `{ip}` | {count} |\n"
    else:
        content += "*No IPs detected in log file.*\n"
        
    content += f"\n## 🚨 Suspicious Activity & Alerts\n"
    if summary['suspicious_activity']:
        for alert in summary['suspicious_activity']:
            content += f"- {alert}\n"
    else:
        content += "✅ *No suspicious activity detected based on current thresholds.*\n"
        
    content += "\n---\n"
    content += "*Disclaimer: This report was generated by an educational and defensive tool. Manual verification of alerts is recommended.*"
    
    with open(OUTPUT_FILENAME, 'w', encoding='utf-8') as f:
        f.write(content)
        
    return os.path.abspath(OUTPUT_FILENAME)
